# permissions for end users to edit games.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: game-editor-role
rules:
- apiGroups:
  - demo.jugsaxony.org
  resources:
  - games
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.jugsaxony.org
  resources:
  - games/status
  verbs:
  - get
