# permissions for end users to edit guesses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: guess-editor-role
rules:
- apiGroups:
  - demo.jugsaxony.org
  resources:
  - guesses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.jugsaxony.org
  resources:
  - guesses/status
  verbs:
  - get
