# permissions for end users to view guesses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: guess-viewer-role
rules:
- apiGroups:
  - demo.jugsaxony.org
  resources:
  - guesses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - demo.jugsaxony.org
  resources:
  - guesses/status
  verbs:
  - get
