---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - demo.jugsaxony.org
  resources:
  - games
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.jugsaxony.org
  resources:
  - games/finalizers
  verbs:
  - update
- apiGroups:
  - demo.jugsaxony.org
  resources:
  - games/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - demo.jugsaxony.org
  resources:
  - guesses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.jugsaxony.org
  resources:
  - guesses/finalizers
  verbs:
  - update
- apiGroups:
  - demo.jugsaxony.org
  resources:
  - guesses/status
  verbs:
  - get
  - patch
  - update
